name: ChatGPT Prompter
description: Sends a user prompt to ChatGPT
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - curl
configuration:
  properties:
    api_key:
      type: string
      description: The environment variable that the OpenAI API key is stored in.  
    buildkite_api_token:
      type: string
      description: The environment variable that the Buildkite API Token is stored in.  
    model:
      type: string
      description: ChatGPT model to use.
      enum: [gpt-4o-mini, gpt-4, gpt-3.5-turbo]
      default: gpt-4o-mini 
    custom_prompt:
      type: string
      description: Additional context to prompt ChatGPT for include in its analysis.