name: ChatGPT Prompter
description: Sends a user prompt to ChatGPT
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - curl
configuration:
  properties:
    api_token_secret_key:
      type: string
      description: The Buildkite Secret key name that stores the OpenAI API Key to use for ChatGPT access.  
    bk_token_secret_key:
      type: string
      description: The Buildkite Secret key name that stores a Buildkite API Token with read-only scope.  
    model:
      type: string
      description: ChatGPT model to use.
      enum: [gpt-4o-mini, gpt-4, gpt-3.5-turbo]
      default: gpt-4o-mini 
    custom_prompt:
      type: string
      description: Additional context to prompt ChatGPT for include in its analysis. 
  required:
    - api_token_secret_key
    - bk_token_secret_key