#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

echo "--- :robot_face: ChatGPT Prompter Plugin"

# Validate required tools
validate_required_tools || exit 1

# Get required plugin configurations
echo "Retrieving OpenAI API Key ..."
# Read plugin configuration for OpenAI API Key
API_KEY=$(plugin_read_config API_KEY "")
# Trim whitespaces from API_KEY
API_KEY=$(echo "${API_KEY}" | xargs)
 
if [ -z "${API_KEY}" ]; then
  echo '❌ Error: Missing OpenAI API Key. Please set the API_KEY in your plugin configuration.'
  exit 1
fi  
validate_api_key "${API_KEY}" || exit 1

echo "Retrieving other plugin configurations ..."
# Load Plugin configuration
MODEL=$(plugin_read_config MODEL "gpt-4o-mini")
CUSTOM_PROMPT=$(plugin_read_config CUSTOM_PROMPT "")
BUILDKITE_API_TOKEN=$(get_bk_api_token)

echo "Using OpenAI API Key: ${API_KEY}"
echo "Using Model: ${MODEL}"
echo "Using Custom Prompt: ${CUSTOM_PROMPT:-Default prompt}"
echo "Using Buildkite API Token: ${BUILDKITE_API_TOKEN:-Not set}"

validate_bk_token "${BUILDKITE_API_TOKEN}" || exit 1

# Send the prompt to ChatGPT
echo "Sending build information to ChatGPT for analysis  ..."
send_prompt "${OPENAI_API_TOKEN}" "${MODEL}" "${CUSTOM_PROMPT}" "${BUILDKITE_API_TOKEN}"  
echo "~~~ Done."